import type { Metadata } from 'next'
import { Noto_Sans_JP, ADLaM_Display } from 'next/font/google'
import '@/styles/globals.css'
import React from 'react'

const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
})

const adlamDisplay = ADLaM_Display({
  weight: '400',
  variable: '--font-adlam-display',
  subsets: ['adlam'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className={`${notoSansJP.variable} ${adlamDisplay.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
